### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.insvtools.frames.FrameType.ordinal()" on videos taken by x4

### ISSUE THREAD

**Issue by wpchen** [alex-plekhanov/insvtools#2]
I'm seeing a java.lang.NullPointerException when using cut or dump-meta command on an insv file recorded by the newly released x4 camera. I've tested on my own file as well as the file provided by this YouTube channel https://www.youtube.com/watch?v=K4GSfKt0Dik (the [link to the file](https://drive.google.com/drive/folders/1Os565ZkoYKHnWckZmSsjQT1vpzGDRmMq?usp=drive_link) is in the video description). Let me know if a smaller sample file would be helpful.

Full log:

```
2024-04-21 21:39:02 [DEBUG] Command line arguments: dump-meta /Users/redacted/Downloads/VID_20240414_135511_00_027.insv
2024-04-21 21:39:02 [INFO ] InsvTools v.1.2-SNAPSHOT, start processing 'dump-meta' command
2024-04-21 21:39:02 [ERROR] Failure: Cannot invoke "org.insvtools.frames.FrameType.ordinal()" because the return value of "org.insvtools.frames.FrameHeader.getFrameType()" is null
java.lang.NullPointerException: Cannot invoke "org.insvtools.frames.FrameType.ordinal()" because the return value of "org.insvtools.frames.FrameHeader.getFrameType()" is null
	at org.insvtools.frames.Frame.create(Frame.java:51)
	at org.insvtools.frames.Frame.read(Frame.java:29)
	at org.insvtools.InsvMetadata.read(InsvMetadata.java:42)
	at org.insvtools.commands.AbstractCommand.readMetaDataOptional(AbstractCommand.java:21)
	at org.insvtools.commands.AbstractCommand.readMetaData(AbstractCommand.java:26)
	at org.insvtools.commands.MetaDumpCommand.run(MetaDumpCommand.java:22)
	at org.insvtools.InsvTools.run(InsvTools.java:115)
	at org.insvtools.InsvTools.main(InsvTools.java:16)
```

**Comment by alex-plekhanov** [comment]
@wpchen thanks for the report. Looks like the file format is slightly changed. There are some trash (but I'm not sure yet) between frames, and new index frame is introduced to find correct frame offset. I've found a way to parse the new format and read the metadata (pushed commit to github), but currently with the new file format tool can be used in read only mode. Perhaps in the near future I will add support for writing too.

**Comment by wpchen** [comment]
Thank you, @alex-plekhanov! I eagerly await when writing / cut works for x4 videos.

**Comment by wpchen** [comment]
@alex-plekhanov, thank you! I can confirm your fix now allows the dump-meta and cut commands to complete. And, consistent with your note about the tool being read-only for x4 videos for now, importing the resulting video from the cut command back into Insta360 Studio incorrectly results in a flat, square, fisheye video. I look forward to that fix whenever it comes!
<img width="1424" alt="Screenshot 2024-04-23 at 11 11 22 AM" src="https://github.com/alex-plekhanov/insvtools/assets/8423070/27b24b29-2f3f-4c24-9b0e-9e1a5ec3abbb">

**Comment by alex-plekhanov** [comment]
@wpchen I've tried to add write support for the new format, but Insta360 Studio still doesn't accept files after cut. This time it fails with error `Check failed (!mediaSamples.empty())` in the log.  Perhaps now there is something wrong with streams inside mp4 file (problem not in insta360 footer), but other video players play processed files as expected.
BTW, functionality for cutting insta360 files now available in Insta360 Studio, so insvtools now only useful if you need command line tool, or want to explore insv internals.

**Comment by wpchen** [comment]
Thanks for trying @alex-plekhanov and understand that it's probably not worth your time to make cutting work. I thought I'd share what I'm running up against in case you had some ideas - the Insta360 Studio solution doesn't quite work for me.

My use case is that I have a single long (~2 hour) video that I want to extract a dozen short (~1 minute each) highlights from. (Timestamps for highlights are supplied by third-party data source).

There are currently two options for me:
(1) use Insta360 Studio to export the entire video then chop up the video programmatically using ffmpeg. Cons: workflow is bottlenecked on initial export of the 2-hour video (export takes ~2x video length to run for me).
(2) for each highlight, use Insta360 Studio GUI to manually set trim start/end and export. Rinse and repeat. Cons: tedious.

This where your tool to cut .insv files came in. I was hoping to programmatically chop up the .insv files using your tool, then batch import into Insta360 Studio, and batch export.

I also looked into [Insta360's SDK](https://github.com/Insta360Develop/MediaSDK-Cpp/tree/master?tab=readme-ov-file#running-test-demo) but it doesn't seem to support specifying start and end times for the export.

**Comment by alex-plekhanov** [comment]
@wpchen, I've finally returned to this problem, and looks like the current version of Insta360 Studio accepts files processed by insvtools (built from the master branch)

**Comment by wpchen** [comment]
Confirmed everything's working. Thank you so much, @alex-plekhanov. This is going to be a huge time-saver for me.
